version: "2"
services:
  nginx:
    image: "nginx:alpine"
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/certs/:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - Network_secure_registry

  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./docker-registry-data:/var/lib/registry
    networks:
      - Network_secure_registry

networks:
  Network_secure_registry: